### PR TITLE
remove unnecessary audio encoders

### PR DESCRIPTION
**Pull request by jjoyce-bittorrent**
fixes the windows build

### CODE REVIEW

**Comment by gzphreak** [comment]
This assumes we use the static ffmpeg binary from now on?

**Comment by gzphreak** [comment]
This assumes we use the static ffmpeg binary from now on?

**Comment by gzphreak** [comment]
This assumes we use the static ffmpeg binary from now on?

**Review by gzphreak — COMMENTED** [review]
This assumes we use the static ffmpeg binary from now on?

**Comment by jjoyce-bittorrent** [comment]
These are audio encoders for existing kodi functionality.
Our transcoding does use the static binary.
Later on will we move away from the static binary and maybe we will have to pull these in but i dont think we will have to.

**Comment by jjoyce-bittorrent** [comment]
These are audio encoders for existing kodi functionality.
Our transcoding does use the static binary.
Later on will we move away from the static binary and maybe we will have to pull these in but i hope we won't have.

**Comment by jjoyce-bittorrent** [comment]
These are audio encoders for existing kodi functionality.
Our transcoding does use the static binary.
Later on will we move away from the static binary and maybe we will have to pull these in but i hope we won't have.

**Review by gzphreak — APPROVED** [review]

**Pull request merged**
